apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-api.name" . }}
  labels:
    {{- include "platform-api.labels" . | nindent 4 }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: {{ .Values.service.scheme | quote }}
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: {{ .Values.service.nlbTargetType | quote }}
    {{- if .Values.service.tls.enabled }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.service.tls.certificateArn | quote }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass }}
  {{- end }}
  selector:
    {{- include "platform-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ if .Values.service.tls.enabled }}443{{ else }}80{{ end }}
      targetPort: http
      protocol: TCP
